// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: assignments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (
ticket_id, agent_id, status
) VALUES (
  $1, $2, $3
)
RETURNING id, ticket_id, agent_id, status, assigned_at
`

type CreateAssignmentParams struct {
	TicketID int64  `json:"ticket_id"`
	AgentID  int64  `json:"agent_id"`
	Status   string `json:"status"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, createAssignment, arg.TicketID, arg.AgentID, arg.Status)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AgentID,
		&i.Status,
		&i.AssignedAt,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM assignments
WHERE id = $1
`

func (q *Queries) DeleteAssignment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAssignment, id)
	return err
}

const getAssignment = `-- name: GetAssignment :one
SELECT assignments.id, ticket_id, agent_id, assignments.status, assigned_at, tickets.id, title, description, tickets.status, assigned_to, tickets.created_at, agents.id, name, agents.status, agents.created_at FROM assignments
JOIN tickets ON assignments.ticket_id = tickets.id
JOIN agents ON assignments.agent_id = agents.id
WHERE assignments.id = $1 
LIMIT 1
`

type GetAssignmentRow struct {
	ID          int64         `json:"id"`
	TicketID    int64         `json:"ticket_id"`
	AgentID     int64         `json:"agent_id"`
	Status      string        `json:"status"`
	AssignedAt  time.Time     `json:"assigned_at"`
	ID_2        int64         `json:"id_2"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Status_2    string        `json:"status_2"`
	AssignedTo  sql.NullInt64 `json:"assigned_to"`
	CreatedAt   time.Time     `json:"created_at"`
	ID_3        int64         `json:"id_3"`
	Name        string        `json:"name"`
	Status_3    string        `json:"status_3"`
	CreatedAt_2 time.Time     `json:"created_at_2"`
}

func (q *Queries) GetAssignment(ctx context.Context, id int64) (GetAssignmentRow, error) {
	row := q.db.QueryRowContext(ctx, getAssignment, id)
	var i GetAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AgentID,
		&i.Status,
		&i.AssignedAt,
		&i.ID_2,
		&i.Title,
		&i.Description,
		&i.Status_2,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.ID_3,
		&i.Name,
		&i.Status_3,
		&i.CreatedAt_2,
	)
	return i, err
}

const getAssignmentForUpdate = `-- name: GetAssignmentForUpdate :one
SELECT id, ticket_id, agent_id, status, assigned_at FROM assignments
WHERE id = $1 LIMIT 1 
FOR NO KEY UPDATE
`

func (q *Queries) GetAssignmentForUpdate(ctx context.Context, id int64) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, getAssignmentForUpdate, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AgentID,
		&i.Status,
		&i.AssignedAt,
	)
	return i, err
}

const getAssignments = `-- name: GetAssignments :many
SELECT assignments.id, ticket_id, agent_id, assignments.status, assigned_at, tickets.id, title, description, tickets.status, assigned_to, tickets.created_at, agents.id, name, agents.status, agents.created_at FROM assignments
JOIN tickets ON assignments.ticket_id = tickets.id
JOIN agents ON assignments.agent_id = agents.id
ORDER BY assignments.id
LIMIT $1
OFFSET $2
`

type GetAssignmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAssignmentsRow struct {
	ID          int64         `json:"id"`
	TicketID    int64         `json:"ticket_id"`
	AgentID     int64         `json:"agent_id"`
	Status      string        `json:"status"`
	AssignedAt  time.Time     `json:"assigned_at"`
	ID_2        int64         `json:"id_2"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Status_2    string        `json:"status_2"`
	AssignedTo  sql.NullInt64 `json:"assigned_to"`
	CreatedAt   time.Time     `json:"created_at"`
	ID_3        int64         `json:"id_3"`
	Name        string        `json:"name"`
	Status_3    string        `json:"status_3"`
	CreatedAt_2 time.Time     `json:"created_at_2"`
}

func (q *Queries) GetAssignments(ctx context.Context, arg GetAssignmentsParams) ([]GetAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssignments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssignmentsRow
	for rows.Next() {
		var i GetAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.AgentID,
			&i.Status,
			&i.AssignedAt,
			&i.ID_2,
			&i.Title,
			&i.Description,
			&i.Status_2,
			&i.AssignedTo,
			&i.CreatedAt,
			&i.ID_3,
			&i.Name,
			&i.Status_3,
			&i.CreatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE assignments SET status = $2
WHERE id = $1 RETURNING id, ticket_id, agent_id, status, assigned_at
`

type UpdateAssignmentParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, updateAssignment, arg.ID, arg.Status)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AgentID,
		&i.Status,
		&i.AssignedAt,
	)
	return i, err
}
